#!/bin/bash

case "$1" in
   (*)
    SELECTED_DIR=$1
    DIR="/opt/ELSM/Server"
    ;;
esac

source $DIR/$SELECTED_DIR/conf.cfg
CONFIG="${DIR}/${SELECTED_DIR}/conf.cfg"
echo "This is the selected files: $SELECTED_DIR"
###############################
###      Version 0.2.2     ###
###############################

cd $INSTALL_LOC/Files/

do_changelog() {
        cat <<EOF >> changelog
1. Added merges from my amazing contributors!
2. And a special thanks to them as well (see menu)
EOF
whiptail --fb --title "ELSM Changelog 0.2.2" --textbox changelog 20 60
rm changelog
}

do_update() {
	cp $CONFIG $DIR/$SELECTED_DIR/conf.cfg.bak
	wget https://raw.githubusercontent.com/kicker22004/ECO_LINUX_SERVER_MANAGER/master/ELSM -O ELSM
	wget https://raw.githubusercontent.com/kicker22004/ECO_LINUX_SERVER_MANAGER/master/Files/conf.cfg -O $DIR/$SELECTED_DIR/conf.cfg
	wget https://raw.githubusercontent.com/kicker22004/ECO_LINUX_SERVER_MANAGER/master/Files/conf.cfg -O $INSTALL_LOC/Files/conf.cfg
	wget https://raw.githubusercontent.com/kicker22004/ECO_LINUX_SERVER_MANAGER/master/Files/update.sh -O update.sh
	wget https://raw.githubusercontent.com/kicker22004/ECO_LINUX_SERVER_MANAGER/master/Files/watch.sh -O watch.sh
	clear
	echo "Root is needed to install ELSM in (/usr/bin/)"
	sudo mv ELSM /usr/bin/
	sudo chmod +x /usr/bin/ELSM
	chmod +x /opt/ELSM/Files/update.sh
	chmod +x /opt/ELSM/Files/watch.sh

##Grab old info and copy it to the new conf.cfg##
#################################################
	source $DIR/$SELECTED_DIR/conf.cfg.bak
	sed -i "s/ECO_VERSION=.*/ECO_VERSION=$ECO_VERSION/g" $CONFIG
	sed -i "s/check=.*/check=$check/g" $CONFIG
	sed -i "s/startonboot=.*/startonboot=$startonboot/g" $CONFIG
}

if [ -f $DIR/$SELECTED_DIR/conf.cfg ]; then
	do_changelog
	do_update
else
	whiptail --msgbox --fb "Sorry it seems that your ELSM installation is not complete. Leaving." 20 60 0
	clear
	echo "No conf.cfg found in ${DIR}/${SELECTED_DIR}" ; exit 1
fi
exit 0
