#!/bin/bash

case "$1" in
   (*)
    SELECTED_DIR=$1
    DIR="/opt/ELSM/Server"
    ;;
esac

source $DIR/$SELECTED_DIR/conf.cfg
CONFIG="${DIR}/${SELECTED_DIR}/conf.cfg"
echo "This is the selected files: $SELECTED_DIR"
###############################
###      Version 0.2.3     ###
###############################

cd $INSTALL_LOC/Files/

do_changelog() {
        cat <<EOF >> changelog
1. More fixes to the Update scripts.
EOF
whiptail --fb --title "ELSM Changelog 0.2.3" --textbox changelog 20 60
rm changelog
}
do_update() {
	cp $CONFIG $DIR/$SELECTED_DIR/conf.cfg.bak
	wget https://raw.githubusercontent.com/$GIT_REPO_USER/ECO_LINUX_SERVER_MANAGER/$DEFAULT_BRANCH/ELSM -O ELSM
	wget https://raw.githubusercontent.com/$GIT_REPO_USER/ECO_LINUX_SERVER_MANAGER/$DEFAULT_BRANCH/Files/conf.cfg -O $INSTALL_LOC/Files/conf.cfg
	wget https://raw.githubusercontent.com/$GIT_REPO_USER/ECO_LINUX_SERVER_MANAGER/$DEFAULT_BRANCH/Files/update.sh -O update.sh
	wget https://raw.githubusercontent.com/$GIT_REPO_USER/ECO_LINUX_SERVER_MANAGER/$DEFAULT_BRANCH/Files/watch.sh -O watch.sh
	cp $INSTALL_LOC/Files/conf.cfg $DIR/$SELECTED_DIR/conf.cfg
	clear
	echo "Root is needed to install ELSM in (/usr/bin/)"
	sudo mv ELSM /usr/bin/
	sudo chmod +x /usr/bin/ELSM
	chmod +x /opt/ELSM/Files/update.sh
	chmod +x /opt/ELSM/Files/watch.sh

##Grab old info and copy it to the new conf.cfg##
#################################################
	source $DIR/$SELECTED_DIR/conf.cfg.bak
	sed -i "s/ECO_VERSION=.*/ECO_VERSION=$ECO_VERSION/g" $CONFIG
	 sed -i "s/ELSM_VERSION=.*/ELSM_VERSION=$ELSM_VERSION/g" $CONFIG
	#New upgrade system
	sed -i "s/GIT_REPO_USER=.*/GIT_REPO_USER=$GIT_REPO_USER/g" $CONFIG
	sed -i "s/DEFAULT_BRANCH=.*/DEFAULT_BRANCH=$DEFAULT_BRANCH/g" $CONFIG
	sed -i "s/SELECTED_DIR=.*/SELECTED_DIR=$SELECTED_DIR/g"
	sed -i "s/PORT=.*/PORT=$PORT/g"
}

if [ -f $DIR/$SELECTED_DIR/conf.cfg ]; then
	do_changelog
	do_update
else
	whiptail --msgbox --fb "Sorry it seems that your ELSM installation is not complete. Leaving." 20 60 0
	clear
	echo "No conf.cfg found in ${DIR}/${SELECTED_DIR}" ; exit 1
fi
exit 0
