#!/bin/bash
INSTALL_LOC=/opt/ELSM
CONFIG=$INSTALL_LOC/Files/conf.cfg
###############################
###      Version 0.0.6     ###
###############################

cd $INSTALL_LOC/Files

do_changelog() {
        cat <<EOF >> changelog
1. Fixes for Debian (Mini)
2. Updated to 6.4.0
EOF
whiptail --fb --title "ELSM Changelog 0.0.7" --textbox changelog 20 60
rm changelog
}

do_update() {
	cp $CONFIG $INSTALL_LOC/Files/conf.cfg.bak
	wget https://raw.githubusercontent.com/kicker22004/ECO_LINUX_SERVER_MANAGER/master/ELSM -O ELSM
	wget https://raw.githubusercontent.com/kicker22004/ECO_LINUX_SERVER_MANAGER/master/Files/conf.cfg -O conf.cfg
	wget https://raw.githubusercontent.com/kicker22004/ECO_LINUX_SERVER_MANAGER/master/Files/update.sh -O update.sh
	wget https://raw.githubusercontent.com/kicker22004/ECO_LINUX_SERVER_MANAGER/master/Files/Config_mods.txt -O Config_mods.txt
	wget https://raw.githubusercontent.com/kicker22004/ECO_LINUX_SERVER_MANAGER/master/Files/ServerVersions.txt -O ServerVersions.txt
	wget https://raw.githubusercontent.com/kicker22004/ECO_LINUX_SERVER_MANAGER/master/Files/watch.sh -O watch.sh
	clear
	echo "Root is needed to install ELSM in (/usr/bin/)"
	sudo mv ELSM /usr/bin/
	sudo chmod +x /usr/bin/ELSM
	chmod +x /opt/ELSM/Files/update.sh
	chmod +x /opt/ELSM/Files/upgrade
	chmod +x /opt/ELSM/Files/watch.sh

##Grab old info and copy it to the new conf.cfg##
#################################################
	source $INSTALL_LOC/Files/conf.cfg.bak
	sed -i "s/ECO_VERSION=.*/ECO_VERSION=$ECO_VERSION/g" $CONFIG
	sed -i "s/check=.*/check=$check/g" $CONFIG
	sed -i "s/startonboot=.*/startonboot=$startonboot/g" $CONFIG
}

if [ -f /opt/ELSM/Files/conf.cfg ]; then
	do_changelog
	do_update
else
	whiptail --msgbox --fb "Sorry it seems that your ELSM installation is not complete. Leaving." 20 60 0
	clear
	echo "No conf.cfg found in /opt/ELSM/Files/" ; exit 1
fi
exit 0
